gui:
  nerdFontsVersion: "3"
  showFileIcons: true

  # Git information
  showBranchCommitHash: true
  showDivergenceFromBaseBranch: arrowAndNumber

  # UI
  showBottomLine: true
  showPanelJumps: true
  showRandomTip: false
  showCommandLog: false

  # Diff
  splitDiff: auto
  border: rounded

  # Panels
  expandedSidePanel: files
  showFileTree: true
  sidePanelWidth: 0.20

  # Catppuccin Mocha
  theme:
    activeBorderColor:
      - "#89b4fa"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    searchingActiveBorderColor:
      - "#f9e2af"
      - bold
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
    inactiveViewSelectedLineBgColor:
      - "#6c7086"
    cherryPickedCommitFgColor:
      - "#89b4fa"
    cherryPickedCommitBgColor:
      - "#45475a"
    markedBaseCommitFgColor:
      - "#89b4fa"
    markedBaseCommitBgColor:
      - "#f9e2af"
    unstagedChangesColor:
      - "#f38ba8"
    defaultFgColor:
      - "#cdd6f4"

  # authorColors:
  #   "*": "#b4befe"

git:
  # Delta = Haupt-Diff-Renderer
  diffRenderers:
    - name: "delta"
      type: "stdinFilter"
      colorArg: "always"
      command: >-
        delta
        --paging=never
        --navigate
        --line-numbers
        --side-by-side
        --true-color=always
        --syntax-theme="Catppuccin-mocha"
        --hyperlinks
        --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"
        --file-decoration-style=none
        --hunk-header-style=file
        --commit-style=bold

  # Git behaviour
  autoFetch: true
  autoRefresh: true

  # Better commit UX
  commit:
    autoWrapCommitMessage: true
    autoWrapWidth: 72

os:
  editCommand: nvim
  editCommandTemplate: >-
    nvim --server {{server}}
    --remote-send '<C-\><C-n>:e {{filename}}<CR>'

customCommands:

  # B = blame current file
  - key: "B"
    context: "files"
    description: "Git blame current file"
    command: "git blame -w -- {{.SelectedFile.Name}}"
    output: terminal

  # G = complete git graph
  - key: "G"
    context: "localBranches"
    description: "Git graph"
    command: >-
      git log
      --graph
      --decorate
      --all
      --oneline
      --date-order
    output: terminal

  # F = file history
  - key: "F"
    context: "files"
    description: "File history"
    command: "git log --follow -- {{.SelectedFile.Name}}"
    output: terminal
